/** @format */

import { Metadata } from "next";
import Script from "next/script";
import { LanguageSync } from "../../components/LanguageSync";
import { THEMES } from "@/config/themes";
import { themeInitScript } from "darkmode-plus-a11y/react/themeInitScript";

const metadata = {
	fr: {
		title: "Simon LM | Spécialiste en Accessibilité Web",
		description:
			"Portfolio de Simon LM, développeur frontend spécialisé en accessibilité web...",
	},
	en: {
		title: "Simon LM | Web Accessibility Specialist",
		description:
			"Simon LM's portfolio - Frontend developer specialized in web accessibility...",
	},
};

export async function generateMetadata({
	params,
}: {
	params: Promise<{ lang: string }>;
}): Promise<Metadata> {
	const { lang } = await params;
	const langKey = lang as keyof typeof metadata;

	// Return the full metadata, not just title and description
	return {
		// Language-specific metadata
		title: metadata[langKey].title,
		description: metadata[langKey].description,

		// Preserve the important metadata from the parent layout
		metadataBase: new URL("https://www.simon-lm.dev"),
		icons: {
			icon: "/favicon.ico",
			shortcut: "/favicon.ico",
			apple: [
				{ url: "/Logo_LostInTab/apple-touch-icon.png", sizes: "180x180" },
			],
		},
		appleWebApp: {
			capable: true,
			statusBarStyle: "default",
			title: "Simon LM",
		},

		alternates: {
			canonical: `/${lang}`,
			languages: {
				fr: "/fr",
				en: "/en",
			},
		},
	};
}

export async function generateStaticParams() {
	return [{ lang: "en" }, { lang: "fr" }];
}

export default async function LangLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: Promise<{ lang: string }>;
}) {
	const { lang } = await params;

	return (
		<>
			{/* Sync Zustand language store with URL lang to prevent hydration mismatch */}
			<LanguageSync lang={lang as "fr" | "en"} />

			{/* Anti-FOUC script: string generated by the package (E4 phase 3),
			    byte-identical to the historical literal — oracle verified. */}
			<Script
				id="theme-script"
				strategy="beforeInteractive"
				dangerouslySetInnerHTML={{
					__html: themeInitScript(THEMES),
				}}
			/>

			{/* Dynamically update the lang attribute */}
			<Script
				id="update-lang"
				strategy="afterInteractive"
				dangerouslySetInnerHTML={{
					__html: `
				document.documentElement.lang = "${lang}";
			  `,
				}}
			/>

			{children}
		</>
	);
}
